spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

api:
  base_url: https://csrng.net/csrng/csrng.php
  random:
    max: 1000000
    min: 0
java:
  random:
    max: 1000000
    min: 0
